### ISSUE TITLE
Solve dummy item creation

### ISSUE THREAD

**Issue by PlanetEfficacy** [PlanetEfficacy/little_shop#10]

**Comment by PlanetEfficacy** [comment]
Basically we need to have a clean way to create object in tests as well as in our dev db. 

class HipsterItemGenerator

adjectives = ["organic", "cage free", "gluten free", "free range", "vintage", "cruelty-free"]
verbs = ["crafted", "harvested", "raised", "cured"]




end

**Comment by tgisg** [comment]
Anyone interested in trying fabrication? https://www.fabricationgem.org/
