### ISSUE TITLE
Admin Item Creation

### ISSUE THREAD

**Issue by case-eee** [PlanetEfficacy/little_shop#113]
As an authenticated Admin:
      I can create an item.
        - An item must have a title, description and price.
        - An item must belong to at least one category.
        - The title and description cannot be empty.
        - The title must be unique for all items in the system.
        - The price must be a valid decimal numeric value and greater than zero.
        - The photo is optional. If not present, a stand-in photo is used. **(PAPERCLIP)**

**Comment by PlanetEfficacy** [comment]
@case-eee We went down a rabbit hole with the paperclip gem. I know tomorrow you and @s-espinosa are doing assessments all day.  I'm wondering if you can recommend a resource to help us get unstuck. We implemented everything except the file upload via paperclip.

**Comment by case-eee** [comment]
We'll be busy most of the day today :( 

Some mod 3 students posted these resources in their slack:
https://github.com/thoughtbot/paperclip/wiki/Paperclip-with-Amazon-S3
https://devcenter.heroku.com/articles/paperclip-s3

I'd also maybe reach out to mod 3 students this afternoon and see if they have time?
