### ISSUE TITLE
Create Wireframes

### ISSUE THREAD

**Issue by case-eee** [PlanetEfficacy/little_shop#2]
Think about what you think the workflow should be on the site. Which of those views is most important?

In addition to the home page wireframe, create wireframes the page immediately following your Log In and the next most important page for your application.

      Examples might be: A users' profile page, a product page, an admin dashboard etc...

**Comment by susiirwin** [comment]
Using Balsamiq to do some basic wireframing for layout and general feel.

**Comment by susiirwin** [comment]
Wireframes have been pushed to Wireframes branch for team review
