### ISSUE TITLE
Checking out

### ISSUE THREAD

**Issue by case-eee** [PlanetEfficacy/little_shop#46]
Background: An existing user and a cart with items

      As a visitor
      When I add items to my cart
      And I visit "/cart"
      And I click "Login or Register to Checkout"
      Then I should be required to login
      When I am logged in
      And I visit my cart
      And when I click "Checkout"
      Then the order should be placed
      And my current page should be "/orders"
      And I should see a message "Order was successfully placed"
      And I should see the order I just placed in a table

**Comment by tgisg** [comment]
@case-eee Card #21 had the link saying "Login or Create Account to Checkout" rather than "Login or Register to Checkout" is this a typo or do we need a new link on the same /cart index page which accomplishes the same thing but says something different?

**Comment by s-espinosa** [comment]
@tgisg Just a typo! No need for a second button to accomplish the same thing. Thanks for checking.

**Comment by case-eee** [comment]
yup - what Sal said 👍

**Comment by tgisg** [comment]
Thanks! :)
