### ISSUE TITLE
Unauthenticated users security

### ISSUE THREAD

**Issue by case-eee** [PlanetEfficacy/little_shop#48]
Background: An unauthenticated user and their abilities

      As an Unauthenticated User
      I cannot view another user's private data, such as current order, etc.
      I should be redirected to login/create account when I try to check out.
      I cannot view the administrator screens or use administrator functionality.
      I cannot make myself an administrator.

**Comment by PlanetEfficacy** [comment]
@kctrlv I took you off this card because I am starting it now.

**Comment by PlanetEfficacy** [comment]
#47 is very similar to #48 (this card). I'm pasting card 47 here so we can see what is already implemented.


Background: An authenticated user

  As an Authenticated User
  I cannot view another user's private data (current or past orders, etc)
  I cannot view the administrator screens or use admin functionality
  I cannot make myself an admin

**Comment by PlanetEfficacy** [comment]
@s-espinosa "Guest User With Items" card #21 says that when a guest user (e.g. unauthenticated user) visits the '/cart' they should not see an option to checkout. They should only see an option to "Login or Create Account to Checkout". This card seems to suggest that an unauthenticated user should be able to click checkout, but we aren't even showing that button to an unauthenticated user. I'm not sure how to redirect when there is no button to click. What are your thoughts?

**Comment by kctrlv** [comment]
@s-espinosa We landed on this solution: There's a cart page that anyone can access, authenticated or not, they can see their items but there will not be a checkout button on that page unless they are logged in. This meets the criteria of the previous cards' specs. The only problem with this solution is there is no redirection happening. 

My idea was that the user should, in their continuance of the attempt to checkout, click that link "Login or create account to checkout", that way they *will* be redirected to the login path and we can assert that path at the end so the user story is tested to its last sentence.

**Comment by s-espinosa** [comment]
@PlanetEfficacy @kctrlv Looks like you already merged, but just to confirm, I think this is in line with the spirit of both cards if I understand your solution correctly.

I'm assuming that if the third line in this story had read as follows there wouldn't have been any confusion/contradiction?

`I should see a button to login/create account when I go to the cart page.`
