### ISSUE TITLE
Admin cannot modify users

### ISSUE THREAD

**Issue by case-eee** [PlanetEfficacy/little_shop#51]
As a logged in Admin
      I can modify my account data
      But I cannot modify any other user's account data

**Comment by PlanetEfficacy** [comment]
@s-espinosa @case-eee I'm reading this to mean any information on a user profile table associated with the admin user. Or, should it just be that the admin can change their username / password, which is what we have on our user table.

**Comment by s-espinosa** [comment]
@PlanetEfficacy I believe the intent of the card is just to let admins change their username/password. If the only information on the user table is username/password is there a difference between the two options you outlined?

Looking at the schema on your development branch, the only additional item that I see is role, and I don't think the intent of this card is to allow admins to make themselves default users. Does that make sense? Let me know.

**Comment by PlanetEfficacy** [comment]
@s-espinosa cool, admin can change their own username and password - on it.
