### ISSUE TITLE
Delete cart upon checkout so that user cannot hit back and checkout again and new order is added to orders list

### ISSUE THREAD

**Issue by tgisg** [PlanetEfficacy/little_shop#74]

**Comment by tgisg** [comment]
On second thought, maybe not. Recheck functionality, particularly if user checks out and then hits back then checks out again. In this case, it is technically working in the sense that clicking checkout again is making a new order, but do you want to bar this kind of thing?

**Comment by PlanetEfficacy** [comment]
I agree we should prevent users from accidentally double creating orders. Are we emptying the cart when a user click's checkout? Does the session reset if I hit back to it's previous state?

**Comment by tgisg** [comment]
I was thinking perhaps the session needs to be destroyed as soon as the order is created.

**Comment by tgisg** [comment]
The problem with a uniqueness validation is it's hard to know what to validate. We certainly don't want to bar a user from ordering the exact same thing she ordered last time, you know? Perhaps destroying the session[:cart] at that moment would solve the problem?
