### ISSUE TITLE
add sad path for when user clicks checkout and nothing is in cart

### ISSUE THREAD

**Issue by tgisg** [PlanetEfficacy/little_shop#79]

**Comment by PlanetEfficacy** [comment]
@kctrlv my understanding is that we don't even show the checkout button on the layout.html.erb unless the cart is not empty. I definitely wrote a ```cart_empty?``` method yesterday.

**Comment by PlanetEfficacy** [comment]
```  def cart_empty?
    session[:cart] && session[:cart].values.sum == 0
  end``` That's in the application controller.

**Comment by tgisg** [comment]
I think when I tried it (before I made this card) something went wrong, but I could be wrong. I'll double check.
